# Generated by Django 4.0.6 on 2022-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, unique=True)),
                ('short_url', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
